// Generated by CoffeeScript 1.6.3
/*
Module dependencies.
*/


(function() {
  var app, config, env, exports, express, fs, http, io, models_path, mongoose, passport, port, server, templatizer, twit, twitter;

  express = require("express");

  http = require("http");

  fs = require("fs");

  passport = require("passport");

  env = process.env.NODE_ENV || "development";

  config = require("./config/config")[env];

  twitter = require("ntwitter");

  twit = new twitter(config.twitter);

  mongoose = require("mongoose");

  templatizer = require("templatizer");

  templatizer(config.root + "/app/assets/jade/templates", config.root + "/app/assets/js/templates/templates.js");

  mongoose.connect(config.db);

  models_path = __dirname + "/app/models";

  fs.readdirSync(models_path).forEach(function(file) {
    if (~file.indexOf(".js")) {
      return require(models_path + "/" + file);
    }
  });

  require("./config/passport")(passport, config);

  app = express();

  server = http.createServer(app);

  require("./config/express")(app, config, passport);

  require("./config/routes")(app, passport);

  port = process.env.PORT || 3000;

  server.listen(port);

  io = require("socket.io").listen(server);

  require("./app/modules/server_connections")(twit, config, io);

  require("./app/modules/cron").cron();

  exports = module.exports = app;

}).call(this);
