// Generated by CoffeeScript 1.6.3
(function() {
  var User, config, cronJob, env, mongoose, tweets, twit, twitter, _;

  cronJob = require("cron").CronJob;

  env = process.env.NODE_ENV || "development";

  config = require("../../config/config")[env];

  twitter = require("ntwitter");

  twit = new twitter(config.twitter);

  tweets = require("../modules/tweets_helper");

  mongoose = require("mongoose");

  User = mongoose.model("User");

  _ = require("underscore");

  exports.cron = function() {
    var tweetsFetch;
    return tweetsFetch = new cronJob({
      cronTime: "* * * * * *",
      onTick: function() {
        return User.find({}, function(err, users) {
          return _(users).each(function(user) {
            return tweets.search(twit, user.keywords, user);
          });
        });
      },
      start: false,
      timeZone: "America/Los_Angeles"
    });
  };

}).call(this);
