// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(twit, config, io) {
    twit.stream("statuses/filter", {
      track: config.app.defaultCompetitors
    }, function(stream) {
      return stream.on("data", function(data) {
        return io.sockets.volatile.emit("tweet", {
          user: data.user.screen_name,
          username: data.user.name,
          userurl: data.user.url,
          avatar: data.user.profile_image_url,
          text: data.text
        });
      });
    });
    return io.sockets.on("connection", function(client) {
      return client.emit("keywords", {
        keywords: config.app.defaultCompetitors
      });
    });
  };

}).call(this);
