// Generated by CoffeeScript 1.6.3
/*
Module dependencies.
*/


(function() {
  var Tweet, User, mongoose, utils, _;

  mongoose = require("mongoose");

  Tweet = mongoose.model("Tweet");

  User = mongoose.model("User");

  utils = require("../../vendor/lib/utils");

  _ = require("underscore");

  exports.search = function(twit, keywords, user) {
    keywords = keywords.split(",");
    return _(keywords).each(function(word) {
      return twit.search(word, {
        count: 100,
        result_type: "recent",
        include_entities: false
      }, function(err, data) {
        if (err) {
          console.warn("Couldn't find: " + word);
        }
        if (data) {
          return data.statuses.forEach(function(tweet) {
            return Tweet.findOne({
              id: tweet.id
            }, function(err, tw) {
              var newTweet;
              if (err) {
                return errorHandler(err);
              }
              if (!tw) {
                newTweet = new Tweet(tweet);
                newTweet.user_id = user._id;
                newTweet.keyword = word;
                newTweet.keywords = keywords.join(",");
                newTweet.save();
                return console.log("New tweet created, id: " + newTweet.id);
              }
            });
          });
        }
      });
    });
  };

}).call(this);
