// Generated by CoffeeScript 1.6.3
/*
Module dependencies.
*/


(function() {
  var express, flash, helpers, mongoStore, pkg;

  express = require("express");

  mongoStore = require("connect-mongo")(express);

  flash = require("connect-flash");

  helpers = require("view-helpers");

  pkg = require("../package.json");

  module.exports = function(app, config, passport) {
    app.set("showStackError", true);
    app.use(express.compress({
      filter: function(req, res) {
        return /json|text|javascript|css/.test(res.getHeader("Content-Type"));
      },
      level: 9
    }));
    app.use(express.favicon());
    app.use(express["static"](config.root + "/app/assets"));
    if (process.env.NODE_ENV !== "test") {
      app.use(express.logger("dev"));
    }
    app.set("views", config.root + "/app/assets/jade");
    app.set("view engine", "jade");
    app.configure(function() {
      app.use(function(req, res, next) {
        res.locals.pkg = pkg;
        return next();
      });
      app.use(express.cookieParser());
      app.use(express.bodyParser());
      app.use(express.methodOverride());
      app.use(express.session({
        secret: "competition_tracker",
        store: new mongoStore({
          url: config.db,
          collection: "sessions"
        })
      }));
      app.use(passport.initialize());
      app.use(passport.session());
      app.use(flash());
      app.use(helpers(pkg.name));
      if (process.env.NODE_ENV !== "test") {
        app.use(express.csrf());
      }
      app.use(function(req, res, next) {
        res.locals.csrf_token = req.session._csrf;
        return next();
      });
      app.use(app.router);
      app.use(function(err, req, res, next) {
        if (err.message && (~err.message.indexOf("not found") || (~err.message.indexOf("Cast to ObjectId failed")))) {
          return next();
        }
        console.error(err.stack);
        return res.status(500).render("500", {
          error: err.stack
        });
      });
      return app.use(function(req, res, next) {
        return res.status(404).render("404", {
          url: req.originalUrl,
          error: "Not found"
        });
      });
    });
    return app.configure("development", function() {
      return app.locals.pretty = true;
    });
  };

}).call(this);
